language: ruby
cache: bundler
rvm:
- 2.2
install:
- openssl aes-256-cbc -K $encrypted_00bf0e382472_key -iv $encrypted_00bf0e382472_iv
  -in ./travis-ci/accounts.enc -out ./travis-ci/accounts.json -d
- bundle install --jobs=3 --retry=3
deploy:
  provider: rubygems
  api_key:
    secure: rUVISr9AOad19PmaFm2tOJulkIaoiGhjpYj2rDUyXp2YQXlr5vPoEg6h85Qe7fNK4cjWOnY1cuUue/Yf03SEEkzIbnvmpAZL0VsPgf6EcyMOAwLUbMbTO+0TNzbBGSAhG7ylpJ0HCVoOJdP3GzJ9JZU3bOTxbKw//a4+VM/zdUOEjXD0j57z2bXvK3VGmiJ3IqmLVT5NC8WLavf5jRuYHhRUj1UjJAtLner+08Azcy3PD1YbcYPTSP8uHa4NjwWYqelMaAKwathEkdFpbrqdklf39UldXSFwP5mLa27m1JtrRoQwPULe0ygMQe4TcTi3cUsZW532dS5Ix1sL3iEn7iC4gtf4RXhSaGD9iuI/Buw/ym/l/4AMJrwOJWvpzJLQdc7KYD8PgNVdwFVQ5UzWMLZTvFXEBK6DGSnGvcOUGbSVUMZUNDxLKN1bHhcNCW2AvF0rq+guT6T4oPzt4tCBvGBMCDR530QoRYNJ9UpneWvX6f+5USDwfdxr+UrvUgMkSRqWS8QSsa7X51/WPLnW3gLkrtzinOpcAJMhhpwbNzw3vW+vJcJBBGB8RmT4dEn2rim6Xk/hB1AqjWbDT7zxqGCIwV/2VxLnooOuD/aVJYfXNW6t/dHZD/J30KFcGO2Le6ZYdauTBlPji/r29ECR4EZ8wpD5jtjZaAc9BvK3/Zk=
  gem: square_connect
  on:
    branch: master
    repo: square/connect-ruby-sdk
