=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SquareConnect::CheckoutApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CheckoutApi' do
  before do
    # run before each test
    @instance = SquareConnect::CheckoutApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutApi' do
    it 'should create an instact of CheckoutApi' do
      expect(@instance).to be_instance_of(SquareConnect::CheckoutApi)
    end
  end

  # unit tests for create_checkout
  # CreateCheckout
  # Creates a [Checkout](#type-checkout) response that links a &#x60;checkoutId&#x60; and &#x60;checkout_page_url&#x60; that customers can be directed to in order to provide their payment information using a payment processing workflow hosted on connect.squareup.com.
  # @param location_id The ID of the business location to associate the checkout with.
  # @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
  # @param [Hash] opts the optional parameters
  # @return [CreateCheckoutResponse]
  describe 'create_checkout test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
