=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::BatchChangeInventoryRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BatchChangeInventoryRequest' do
  before do
    # run before each test
    @instance = SquareConnect::BatchChangeInventoryRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BatchChangeInventoryRequest' do
    it 'should create an instact of BatchChangeInventoryRequest' do
      expect(@instance).to be_instance_of(SquareConnect::BatchChangeInventoryRequest)
    end
  end
  describe 'test attribute "idempotency_key"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "changes"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ignore_unchanged_counts"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

