=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::CatalogV1Id
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CatalogV1Id' do
  before do
    # run before each test
    @instance = SquareConnect::CatalogV1Id.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CatalogV1Id' do
    it 'should create an instact of CatalogV1Id' do
      expect(@instance).to be_instance_of(SquareConnect::CatalogV1Id)
    end
  end
  describe 'test attribute "catalog_v1_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "location_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

