=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::CatalogQuerySortedAttribute
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CatalogQuerySortedAttribute' do
  before do
    # run before each test
    @instance = SquareConnect::CatalogQuerySortedAttribute.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CatalogQuerySortedAttribute' do
    it 'should create an instact of CatalogQuerySortedAttribute' do
      expect(@instance).to be_instance_of(SquareConnect::CatalogQuerySortedAttribute)
    end
  end
  describe 'test attribute "attribute_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "initial_attribute_value"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sort_order"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DESC", "ASC"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.sort_order = value }.not_to raise_error
       #end
    end
  end

end

