=begin
Square Connect API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::CreateOrderRequestOrder
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateOrderRequestOrder' do
  before do
    # run before each test
    @instance = SquareConnect::CreateOrderRequestOrder.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateOrderRequestOrder' do
    it 'should create an instact of CreateOrderRequestOrder' do
      @instance.should be_a(SquareConnect::CreateOrderRequestOrder) 
    end
  end
  describe 'test attribute "reference_id"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "line_items"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

