=begin
Square Connect API

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::ListCustomersResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ListCustomersResponse' do
  before do
    # run before each test
    @instance = SquareConnect::ListCustomersResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ListCustomersResponse' do
    it 'should create an instact of ListCustomersResponse' do
      @instance.should be_a(SquareConnect::ListCustomersResponse) 
    end
  end
  describe 'test attribute "errors"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "customers"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "cursor"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

