=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::ListCatalogRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ListCatalogRequest' do
  before do
    # run before each test
    @instance = SquareConnect::ListCatalogRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ListCatalogRequest' do
    it 'should create an instact of ListCatalogRequest' do
      expect(@instance).to be_instance_of(SquareConnect::ListCatalogRequest)
    end
  end
  describe 'test attribute "cursor"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "types"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

