=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::ShiftSort
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShiftSort' do
  before do
    # run before each test
    @instance = SquareConnect::ShiftSort.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShiftSort' do
    it 'should create an instact of ShiftSort' do
      expect(@instance).to be_instance_of(SquareConnect::ShiftSort)
    end
  end
  describe 'test attribute "field"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["START_AT", "END_AT", "CREATED_AT", "UPDATED_AT"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.field = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "order"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DESC", "ASC"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.order = value }.not_to raise_error
       #end
    end
  end

end

