=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::V1ListOrdersRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V1ListOrdersRequest' do
  before do
    # run before each test
    @instance = SquareConnect::V1ListOrdersRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1ListOrdersRequest' do
    it 'should create an instact of V1ListOrdersRequest' do
      expect(@instance).to be_instance_of(SquareConnect::V1ListOrdersRequest)
    end
  end
  describe 'test attribute "order"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DESC", "ASC"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.order = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "limit"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "batch_token"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

