=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class CardBrand
    
    OTHER_BRAND = "OTHER_BRAND".freeze
    VISA = "VISA".freeze
    MASTERCARD = "MASTERCARD".freeze
    AMERICAN_EXPRESS = "AMERICAN_EXPRESS".freeze
    DISCOVER = "DISCOVER".freeze
    DISCOVER_DINERS = "DISCOVER_DINERS".freeze
    JCB = "JCB".freeze
    CHINA_UNIONPAY = "CHINA_UNIONPAY".freeze
    SQUARE_GIFT_CARD = "SQUARE_GIFT_CARD".freeze
  end

end
