=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class CatalogObjectType
    
    ITEM = "ITEM".freeze
    IMAGE = "IMAGE".freeze
    CATEGORY = "CATEGORY".freeze
    ITEM_VARIATION = "ITEM_VARIATION".freeze
    TAX = "TAX".freeze
    DISCOUNT = "DISCOUNT".freeze
    MODIFIER_LIST = "MODIFIER_LIST".freeze
    MODIFIER = "MODIFIER".freeze
  end

end
