=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class MeasurementUnitLength
    
    IMPERIAL_INCH = "IMPERIAL_INCH".freeze
    IMPERIAL_FOOT = "IMPERIAL_FOOT".freeze
    IMPERIAL_YARD = "IMPERIAL_YARD".freeze
    IMPERIAL_MILE = "IMPERIAL_MILE".freeze
    METRIC_MILLIMETER = "METRIC_MILLIMETER".freeze
    METRIC_CENTIMETER = "METRIC_CENTIMETER".freeze
    METRIC_METER = "METRIC_METER".freeze
    METRIC_KILOMETER = "METRIC_KILOMETER".freeze
  end

end
