=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class TaxCalculationPhase
    
    SUBTOTAL_PHASE = "TAX_SUBTOTAL_PHASE".freeze
    TOTAL_PHASE = "TAX_TOTAL_PHASE".freeze
  end

end
