=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class TenderCardDetailsStatus
    
    AUTHORIZED = "AUTHORIZED".freeze
    CAPTURED = "CAPTURED".freeze
    VOIDED = "VOIDED".freeze
    FAILED = "FAILED".freeze
  end

end
