=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class V1AdjustInventoryRequestAdjustmentType
    
    SALE = "SALE".freeze
    RECEIVE_STOCK = "RECEIVE_STOCK".freeze
    MANUAL_ADJUST = "MANUAL_ADJUST".freeze
  end

end
