=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class V1MerchantAccountType
    
    LOCATION = "LOCATION".freeze
    BUSINESS = "BUSINESS".freeze
  end

end
