=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class V1OrderState
    
    PENDING = "PENDING".freeze
    OPEN = "OPEN".freeze
    COMPLETED = "COMPLETED".freeze
    CANCELED = "CANCELED".freeze
    REFUNDED = "REFUNDED".freeze
    REJECTED = "REJECTED".freeze
  end

end
