=begin
#Square Connect API

OpenAPI spec version: 2.0
Contact: developers@squareup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SquareConnect
  class Weekday
    
    MON = "MON".freeze
    TUE = "TUE".freeze
    WED = "WED".freeze
    THU = "THU".freeze
    FRI = "FRI".freeze
    SAT = "SAT".freeze
    SUN = "SUN".freeze
  end

end
